import { IAssignmentRepository } from '../../../application/assignments/repositories/IAssignmentRepository';
import {
  CreateAssignmentDTO,
  UpdateAssignmentDTO,
  AssignmentResponseDTO,
  SubmissionResponseDTO,
  PaginatedResponseDTO,
  ReviewSubmissionDTO
} from '../dtos/AssignmentDTOs';
import { AssignmentStatus, SubmissionStatus } from '../../../domain/assignments/enums/AssignmentEnums';
import { Assignment } from '../../../domain/assignments/entities/Assignment';
import { AssignmentMapper } from '../../../infrastructure/repositories/assignments/mappers/AssignmentMapper';
import {
  IGetAssignmentsUseCase,
  IGetAssignmentByIdUseCase,
  ICreateAssignmentUseCase,
  IUpdateAssignmentUseCase,
  IDeleteAssignmentUseCase,
  IGetSubmissionsUseCase,
  IGetSubmissionByIdUseCase,
  IReviewSubmissionUseCase,
  IGetAnalyticsUseCase
} from "./IAssignmentUseCases";
import { AnalyticsData } from '../dtos/AnalyticsDTOs';
import {
  AssignmentNotFoundError,
  SubmissionNotFoundError,
  AssignmentValidationError
} from '../../../domain/assignments/errors/AssignmentErrors';

export class GetAssignmentsUseCase implements IGetAssignmentsUseCase {
  constructor(private assignmentRepository: IAssignmentRepository) { }

  async execute(params: { subject?: string; status?: string; page?: number; limit?: number; search?: string }): Promise<PaginatedResponseDTO<AssignmentResponseDTO>> {
    const { assignments, total, page, limit } = await this.assignmentRepository.getAssignments(
      params.subject,
      params.status,
      params.page,
      params.limit,
      params.search
    );

    const assignmentDTOs = assignments.map(assignment => AssignmentMapper.toDTO(assignment));

    return {
      data: assignmentDTOs,
      total,
      page,
      limit
    };
  }
}

export class GetAssignmentByIdUseCase implements IGetAssignmentByIdUseCase {
  constructor(private assignmentRepository: IAssignmentRepository) { }

  async execute(params: { id: string }): Promise<AssignmentResponseDTO> {
    const assignment = await this.assignmentRepository.getAssignmentById(params.id);
    if (!assignment) {
      throw new AssignmentNotFoundError(params.id);
    }
    return AssignmentMapper.toDTO(assignment);
  }
}

export class CreateAssignmentUseCase implements ICreateAssignmentUseCase {
  constructor(private assignmentRepository: IAssignmentRepository) { }

  async execute(params: CreateAssignmentDTO): Promise<AssignmentResponseDTO> {
    const assignment = Assignment.create({
      id: '', // ID will be generated by persistence or we can generate a UUID here if wanted
      title: params.title,
      subject: params.subject,
      description: params.description,
      maxMarks: params.maxMarks,
      dueDate: params.dueDate,
      files: params.files ? params.files.map(f => ({ fileName: f.originalname, fileUrl: f.path, fileSize: f.size })) : []
    });

    const newAssignment = await this.assignmentRepository.createAssignment(assignment);
    return AssignmentMapper.toDTO(newAssignment);
  }
}

export class UpdateAssignmentUseCase implements IUpdateAssignmentUseCase {
  constructor(private assignmentRepository: IAssignmentRepository) { }

  async execute(params: UpdateAssignmentDTO): Promise<AssignmentResponseDTO> {
    const assignment = await this.assignmentRepository.getAssignmentById(params.id);
    if (!assignment) {
      throw new AssignmentNotFoundError(params.id);
    }

    assignment.update({
      title: params.title,
      subject: params.subject,
      description: params.description,
      maxMarks: params.maxMarks,
      dueDate: params.dueDate,
      files: params.files ? params.files.map(f => ({ fileName: f.originalname, fileUrl: f.path, fileSize: f.size })) : undefined,
      status: params.status
    });

    const updatedAssignment = await this.assignmentRepository.updateAssignment(params.id, assignment);
    if (!updatedAssignment) {
      throw new AssignmentValidationError('Update failed');
    }

    return AssignmentMapper.toDTO(updatedAssignment);
  }
}

export class DeleteAssignmentUseCase implements IDeleteAssignmentUseCase {
  constructor(private assignmentRepository: IAssignmentRepository) { }

  async execute(params: { id: string }): Promise<{ message: string }> {
    const deleted = await this.assignmentRepository.deleteAssignment(params.id);
    if (!deleted) {
      throw new AssignmentNotFoundError(params.id);
    }
    return { message: "Assignment deleted successfully" };
  }
}

export class GetSubmissionsUseCase implements IGetSubmissionsUseCase {
  constructor(private assignmentRepository: IAssignmentRepository) { }

  async execute(params: { assignmentId: string; page?: number; limit?: number; search?: string; status?: string }): Promise<PaginatedResponseDTO<SubmissionResponseDTO>> {
    const { submissions, total, page, limit } = await this.assignmentRepository.getSubmissions(
      params.assignmentId,
      params.page,
      params.limit,
      params.search,
      params.status
    );

    const mappedSubmissions = submissions.map(s => AssignmentMapper.submissionToDTO(s));

    return {
      data: mappedSubmissions,
      total,
      page,
      limit
    };
  }
}

export class GetSubmissionByIdUseCase implements IGetSubmissionByIdUseCase {
  constructor(private assignmentRepository: IAssignmentRepository) { }

  async execute(params: { assignmentId: string; submissionId: string }): Promise<SubmissionResponseDTO> {
    const submission = await this.assignmentRepository.getSubmissionById(params.assignmentId, params.submissionId);
    if (!submission) {
      throw new SubmissionNotFoundError(params.submissionId);
    }
    return AssignmentMapper.submissionToDTO(submission);
  }
}

export class ReviewSubmissionUseCase implements IReviewSubmissionUseCase {
  constructor(private assignmentRepository: IAssignmentRepository) { }

  async execute(params: ReviewSubmissionDTO): Promise<SubmissionResponseDTO> {
    const updatedSubmission = await this.assignmentRepository.reviewSubmission(
      params.assignmentId,
      params.submissionId,
      params.marks,
      params.feedback,
      params.status,
      params.isLate
    );

    if (!updatedSubmission) {
      throw new SubmissionNotFoundError(params.submissionId);
    }

    return AssignmentMapper.submissionToDTO(updatedSubmission);
  }
}

export class GetAnalyticsUseCase implements IGetAnalyticsUseCase {
  constructor(private readonly assignmentRepository: IAssignmentRepository) { }

  async execute(): Promise<AnalyticsData> {
    const analytics = await this.assignmentRepository.getAnalytics();
    return analytics;
  }
}

