import { IAssignmentRepository } from '../../../application/assignments/repositories/IAssignmentRepository';
import {
  CreateAssignmentDTO,
  UpdateAssignmentDTO,
  AssignmentResponseDTO,
  SubmissionResponseDTO,
  PaginatedResponseDTO,
  ReviewSubmissionDTO
} from '../dtos/AssignmentDTOs';

import { Assignment } from '../../../domain/assignments/entities/Assignment';
import { AssignmentMapper } from '../../../infrastructure/repositories/assignments/mappers/AssignmentMapper';
import {
  IGetAssignmentsUseCase,
  IGetAssignmentByIdUseCase,
  ICreateAssignmentUseCase,
  IUpdateAssignmentUseCase,
  IDeleteAssignmentUseCase,
  IGetSubmissionsUseCase,
  IGetSubmissionByIdUseCase,
  IReviewSubmissionUseCase,
  IGetAnalyticsUseCase
} from "./IAssignmentUseCases";
import { AnalyticsData } from '../dtos/AnalyticsDTOs';
import {
  AssignmentNotFoundError,
  SubmissionNotFoundError,
  AssignmentValidationError
} from '../../../domain/assignments/errors/AssignmentErrors';
import { IStorageService } from '../../../application/shared/services/IStorageService';
import Logger from '../../../shared/utils/logger';

export class GetAssignmentsUseCase implements IGetAssignmentsUseCase {
  constructor(private assignmentRepository: IAssignmentRepository) { }

  async execute(params: { subject?: string; status?: string; page?: number; limit?: number; search?: string }): Promise<PaginatedResponseDTO<AssignmentResponseDTO>> {
    const { assignments, total, page, limit } = await this.assignmentRepository.getAssignments(
      params.subject,
      params.status,
      params.page,
      params.limit,
      params.search
    );

    const assignmentDTOs = assignments.map(assignment => AssignmentMapper.toDTO(assignment));

    return {
      data: assignmentDTOs,
      total,
      page,
      limit
    };
  }
}

export class GetAssignmentByIdUseCase implements IGetAssignmentByIdUseCase {
  constructor(private assignmentRepository: IAssignmentRepository) { }

  async execute(params: { id: string }): Promise<AssignmentResponseDTO> {
    const assignment = await this.assignmentRepository.getAssignmentById(params.id);
    if (!assignment) {
      throw new AssignmentNotFoundError(params.id);
    }
    return AssignmentMapper.toDTO(assignment);
  }
}

export class CreateAssignmentUseCase implements ICreateAssignmentUseCase {
  constructor(
    private assignmentRepository: IAssignmentRepository,
    private storageService: IStorageService
  ) { }

  async execute(params: CreateAssignmentDTO): Promise<AssignmentResponseDTO> {
    try {
      const assignment = Assignment.create({
        id: '', // ID will be generated by persistence or we can generate a UUID here if wanted
        title: params.title,
        subject: params.subject,
        description: params.description,
        maxMarks: params.maxMarks,
        dueDate: params.dueDate,
        files: params.files ? params.files.map(f => ({ fileName: f.originalname, fileUrl: f.path, fileSize: f.size })) : []
      });

      const newAssignment = await this.assignmentRepository.createAssignment(assignment);
      return AssignmentMapper.toDTO(newAssignment);
    } catch (error) {
      // Cleanup: If DB creation fails, delete uploaded files
      if (params.files && params.files.length > 0) {
        Logger.warn('⚠️ DB Creation failed for assignment. Deleting uploaded files...');
        for (const file of params.files) {
          await this.storageService.deleteFile(file.path);
        }
      }
      throw error;
    }
  }
}

export class UpdateAssignmentUseCase implements IUpdateAssignmentUseCase {
  constructor(
    private assignmentRepository: IAssignmentRepository,
    private storageService: IStorageService
  ) { }

  async execute(params: UpdateAssignmentDTO): Promise<AssignmentResponseDTO> {
    const assignment = await this.assignmentRepository.getAssignmentById(params.id);
    if (!assignment) {
      throw new AssignmentNotFoundError(params.id);
    }

    const oldFiles = assignment.files || [];
    const newFilesUpload = params.files ? params.files.map(f => ({ fileName: f.originalname, fileUrl: f.path, fileSize: f.size })) : undefined;

    // Check if files are being updated (replaced)
    // Note: This logic assumes if `params.files` is present, it REPLACES all existing files.
    // If the requirement is to APPEND, logic would be different. Based on `assignment.update` below, it replaces.

    assignment.update({
      title: params.title,
      subject: params.subject,
      description: params.description,
      maxMarks: params.maxMarks,
      dueDate: params.dueDate,
      files: newFilesUpload,
      status: params.status
    });

    try {
      const updatedAssignment = await this.assignmentRepository.updateAssignment(params.id, assignment);
      if (!updatedAssignment) {
        throw new AssignmentValidationError('Update failed');
      }

      // Success: If new files were uploaded and they replaced old ones, delete old files
      if (newFilesUpload && oldFiles.length > 0) {
        Logger.info('🗑️ Deleting old assignment files after update...');
        for (const oldFile of oldFiles) {
          await this.storageService.deleteFile(oldFile.fileUrl);
        }
      }

      return AssignmentMapper.toDTO(updatedAssignment);
    } catch (error) {
      // Failure: If DB update failed, delete the NEWLY uploaded files
      if (params.files && params.files.length > 0) {
        Logger.warn('⚠️ DB Update failed for assignment. Deleting newly uploaded files...');
        for (const file of params.files) {
          await this.storageService.deleteFile(file.path);
        }
      }
      throw error;
    }
  }
}

export class DeleteAssignmentUseCase implements IDeleteAssignmentUseCase {
  constructor(
    private assignmentRepository: IAssignmentRepository,
    private storageService: IStorageService
  ) { }

  async execute(params: { id: string }): Promise<{ message: string }> {
    const assignment = await this.assignmentRepository.getAssignmentById(params.id);
    if (!assignment) {
      throw new AssignmentNotFoundError(params.id);
    }

    const deleted = await this.assignmentRepository.deleteAssignment(params.id);
    if (!deleted) {
      // Should theoretically catch above, but safety check
      throw new AssignmentNotFoundError(params.id);
    }

    // Cleanup files
    if (assignment.files && assignment.files.length > 0) {
      Logger.info(`🗑️ Deleting files for deleted assignment ${params.id}...`);
      for (const file of assignment.files) {
        await this.storageService.deleteFile(file.fileUrl);
      }
    }

    return { message: "Assignment deleted successfully" };
  }
}

export class GetSubmissionsUseCase implements IGetSubmissionsUseCase {
  constructor(private assignmentRepository: IAssignmentRepository) { }

  async execute(params: { assignmentId: string; page?: number; limit?: number; search?: string; status?: string }): Promise<PaginatedResponseDTO<SubmissionResponseDTO>> {
    const { submissions, total, page, limit } = await this.assignmentRepository.getSubmissions(
      params.assignmentId,
      params.page,
      params.limit,
      params.search,
      params.status
    );

    const mappedSubmissions = submissions.map(s => AssignmentMapper.submissionToDTO(s));

    return {
      data: mappedSubmissions,
      total,
      page,
      limit
    };
  }
}

export class GetSubmissionByIdUseCase implements IGetSubmissionByIdUseCase {
  constructor(private assignmentRepository: IAssignmentRepository) { }

  async execute(params: { assignmentId: string; submissionId: string }): Promise<SubmissionResponseDTO> {
    const submission = await this.assignmentRepository.getSubmissionById(params.assignmentId, params.submissionId);
    if (!submission) {
      throw new SubmissionNotFoundError(params.submissionId);
    }
    return AssignmentMapper.submissionToDTO(submission);
  }
}

export class ReviewSubmissionUseCase implements IReviewSubmissionUseCase {
  constructor(private assignmentRepository: IAssignmentRepository) { }

  async execute(params: ReviewSubmissionDTO): Promise<SubmissionResponseDTO> {
    const updatedSubmission = await this.assignmentRepository.reviewSubmission(
      params.assignmentId,
      params.submissionId,
      params.marks,
      params.feedback,
      params.status,
      params.isLate
    );

    if (!updatedSubmission) {
      throw new SubmissionNotFoundError(params.submissionId);
    }

    return AssignmentMapper.submissionToDTO(updatedSubmission);
  }
}

export class GetAnalyticsUseCase implements IGetAnalyticsUseCase {
  constructor(private readonly assignmentRepository: IAssignmentRepository) { }

  async execute(): Promise<AnalyticsData> {
    const analytics = await this.assignmentRepository.getAnalytics();
    return analytics;
  }
}

