import { VideoStatus } from '../enums/VideoStatus';
import { IVideo, IDiplomaInfo } from './VideoTypes';

export { VideoStatus };

export class Video {
    id: string;
    title: string;
    duration: string;
    uploadedAt: Date;
    module: number;
    status: VideoStatus;
    diplomaId: string;
    description: string;
    videoUrl: string;
    diploma?: IDiplomaInfo;

    constructor(props: IVideo) {
        this.id = props.id;
        this.title = props.title;
        this.duration = props.duration;
        this.uploadedAt = props.uploadedAt;
        this.module = props.module;
        this.status = props.status;
        this.diplomaId = props.diplomaId || '';
        this.description = props.description;
        this.videoUrl = props.videoUrl || '';
        this.diploma = props.diploma;
    }

    // Determine if static create is needed. If it's just a helper for instantiation with defaults:
    static create(props: Omit<IVideo, 'id' | 'uploadedAt'>): Video {
        return new Video({
            ...props,
            id: '', // To be generated by database or ID generator service
            uploadedAt: new Date(),
        });
    }
}

export interface VideoFilter {
    diplomaId?: string;
    status?: string;
    startDate?: Date;
    endDate?: Date;
    search?: string;
    id?: string;
}